/* Golmok content data — edit this file to add districts & spots.
   Every user-visible string is a {en, ja, zh, ko} object.
   Spot fields: id, name (latin), ko (korean name), cat, price, badges[], tip, order,
                checked ('YYYY-MM' — 웹 검증으로 실존·영업을 확인한 시점. 없으면 뷰가 "확인 전"이라고 말한다).
   District fields: id, tile, tileClass, full, mapArea, name, hangul, region,
                    tagline, tags, stats{station,walk,best}, story, route[], spots[]. */

const BADGES = {
  en_menu:  {label:{en:'English menu', ja:'英語メニュー', zh:'英文菜单', ko:'영어 메뉴'}, warn:false},
  pic_menu: {label:{en:'Photo menu', ja:'写真メニュー', zh:'图片菜单', ko:'사진 메뉴'}, warn:false},
  tax:      {label:{en:'Tax refund', ja:'免税対応', zh:'可退税', ko:'택스리펀'}, warn:false},
  card:     {label:{en:'Cards OK', ja:'カード可', zh:'可刷卡', ko:'카드 OK'}, warn:false},
  veg:      {label:{en:'Veg options', ja:'ベジ対応', zh:'素食选项', ko:'채식 옵션'}, warn:false},
  late:     {label:{en:'Open late', ja:'深夜営業', zh:'营业到深夜', ko:'심야 영업'}, warn:false},
  cash:     {label:{en:'Cash preferred', ja:'現金推奨', zh:'建议现金', ko:'현금 추천'}, warn:true},
  queue:    {label:{en:'Expect a line', ja:'行列あり', zh:'常排队', ko:'웨이팅 있음'}, warn:true},
};
const FILTERS = ['en_menu','veg','late'];

const NOW = [
  {when:{en:'Oct 3–11 · Gongju', ja:'10月3〜11日 · 公州', zh:'10月3–11日 · 公州', ko:'10월 3–11일 · 공주'},
   t:{en:'Baekje Cultural Festival', ja:'百済文化祭', zh:'百济文化节', ko:'백제문화제'},
   p:{en:'Lantern-lit riverside in the old capital.', ja:'古都の川辺を灯すランタン。', zh:'古都河畔的灯笼夜景。', ko:'옛 수도의 강변을 밝히는 유등.'}},
  {when:{en:'Year-round · Seongsu', ja:'通年 · 聖水', zh:'常年 · 圣水', ko:'연중 · 성수'},
   t:{en:'Pop-up radar: Yeonmujang-gil', ja:'ポップアップ速報：練武場通り', zh:'快闪雷达：练武场街', ko:'팝업 레이더: 연무장길'},
   p:{en:'New pop-ups keep opening along Yeonmujang-gil, week after week.', ja:'練武場通り沿いでは毎週のように新しいポップアップが開きます。', zh:'练武场街一带每周都有新的快闪店开张。', ko:'연무장길 일대엔 주마다 새 팝업이 열립니다.'}},
  {when:{en:'Oct 21–25 · Gangneung', ja:'10月21〜25日 · 江陵', zh:'10月21–25日 · 江陵', ko:'10월 21–25일 · 강릉'},
   t:{en:'Gangneung Coffee Festival', ja:'江陵コーヒー祭り', zh:'江陵咖啡节', ko:'강릉커피축제'},
   p:{en:'Korea’s coffee capital, in its best season.', ja:'韓国コーヒーの都・江陵が、いちばんいい季節を迎えます。', zh:'韩国咖啡之都的最佳季节。', ko:'커피의 도시 강릉이 가장 좋은 계절.'}},
];

const KNOW = [
  {k:{en:'No tipping. Ever.', ja:'チップは不要', zh:'无需小费', ko:'팁 문화 없음'},
   v:{en:'Not at restaurants, cafes, or taxis. It can even confuse people.', ja:'レストランでもカフェでもタクシーでも不要です。渡すとかえって戸惑われることも。', zh:'餐厅、咖啡店、出租车都不需要。给了反而可能让对方不知所措。', ko:'식당·카페·택시 어디에서도 팁은 안 줘요. 주면 오히려 받는 사람이 당황할 수 있어요.'}},
  {k:{en:'Get a T-money card', ja:'T-moneyカードを買う', zh:'买一张T-money卡', ko:'티머니 카드'},
   v:{en:'Any convenience store. Works on subway, bus, taxis, even some shops.', ja:'コンビニで購入可。地下鉄・バス・タクシーのほか、使えるお店もあります。', zh:'便利店有售，地铁、公交、出租车通用，部分商店也能刷。', ko:'편의점에서 살 수 있어요. 지하철·버스·택시는 물론 일부 가게에서도 써요.'}},
  {k:{en:'Tax refund from ₩15,000', ja:'₩15,000から免税', zh:'满₩15,000可退税', ko:'₩15,000부터 택스리펀'},
   v:{en:'Look for the sign, keep your passport handy at checkout.', ja:'対象店のマークを確認し、会計時にパスポートを。', zh:'认准标志，结账时出示护照。', ko:'택스리펀 표시가 있는 매장인지 보고, 계산할 땐 여권을 챙겨 두세요.'}},
  {k:{en:'Cards mostly work', ja:'カードはほぼ使える', zh:'刷卡基本无忧', ko:'카드는 거의 다 됨'},
   v:{en:'But carry ₩20,000 cash for markets and street stalls.', ja:'ただし市場・屋台用に₩2万の現金を。', zh:'但逛市场、吃路边摊最好备上₩2万现金。', ko:'단, 시장과 노점용으로 현금 2만 원은 챙기세요.'}},
  {k:{en:'Naver Map > Google', ja:'地図はNaver Map', zh:'地图用Naver Map', ko:'지도는 네이버지도'},
   v:{en:'Google Maps is limited in Korea. We deep-link every spot for you.', ja:'韓国ではGoogleマップは不完全。各店へのリンクを用意。', zh:'谷歌地图在韩国不好用，我们为每家店提供直达链接。', ko:'구글맵은 한국에서 반쪽짜리예요. 가게마다 지도 바로가기를 달아 뒀어요.'}},
  {k:{en:'Late is normal', ja:'夜が長い国', zh:'夜生活很正常', ko:'밤이 긴 나라'},
   v:{en:'Dinner at 9pm, second round after. Markets close early though.', ja:'21時の夕食も普通で、そのあと二次会へ。ただし市場は早じまい。', zh:'晚上9点吃晚饭很常见，吃完还会续摊。不过市场关门早。', ko:'밤 9시에 저녁 먹고 2차까지 가는 것도 흔해요. 다만 시장은 일찍 닫아요.'}},
];

const DISTRICTS = [
  /* ============ SEONGSU — full guide ============ */
  {
    id:'seongsu', tile:'성수', tileClass:'t-seongsu', full:true, mapArea:'성수동',
    name:{en:'Seongsu', ja:'聖水（ソンス）', zh:'圣水洞', ko:'성수'},
    hangul:'성수동',
    region:{en:'East Seoul', ja:'ソウル東部', zh:'首尔东部', ko:'서울 동부'},
    tagline:{
      en:'Shoe factories turned into Korea’s coolest cafes and pop-ups.',
      ja:'靴工場がカフェとポップアップの聖地に変わった街。',
      zh:'制鞋工厂变身韩国最潮的咖啡馆与快闪店。',
      ko:'수제화 공장이 카페와 팝업의 성지가 된 동네.'},
    tags:{en:['Cafes','Pop-ups','Vintage'], ja:['カフェ','ポップアップ','古着'], zh:['咖啡','快闪店','古着'], ko:['카페','팝업','빈티지']},
    stats:{station:{en:'Seongsu / Ttukseom (Line 2)', ja:'聖水駅・トゥクソム（纛島）駅（2号線）', zh:'圣水/纛岛站（2号线）', ko:'성수·뚝섬역 (2호선)'},
           walk:{en:'~20 min radius', ja:'徒歩約20分圏', zh:'约20分钟范围', ko:'도보 20분 반경'},
           best:{en:'Weekday 11:00–18:00', ja:'平日 11:00–18:00', zh:'工作日 11:00–18:00', ko:'평일 11–18시'}},
    story:{
      en:'Until the 2010s this was a working district of handmade-shoe factories and warehouses. The factories never fully left — they just share the streets now with roasteries, galleries and one-week brand pop-ups. That mix of red brick, forklifts and flat whites is exactly why Koreans call it their Brooklyn. Come on a weekday if you can: on weekends the neighborhood gets loved a little too much.',
      ja:'2010年代までここは手作り靴の工場と倉庫の町でした。工場がすべて出ていったわけではなく、今もロースタリーやギャラリー、ブランドの1週間限定ポップアップと通りを分け合っています。赤レンガとフォークリフトとフラットホワイトが同居する風景こそ、韓国人がここを「ソウルのブルックリン」と呼ぶ理由です。できれば平日に来てください。週末はちょっと人が多すぎるくらいです。',
      zh:'直到2010年代，这里还是手工制鞋厂和仓库的聚集地。工厂并没有全部离开，只是如今和咖啡烘焙坊、画廊、为期一周的品牌快闪店共用这片街巷。红砖、叉车与Flat White共存的画面，正是韩国人称它为“首尔布鲁克林”的原因。能的话尽量工作日来，周末人有点太多了。',
      ko:'2010년대까지 이곳은 수제화 공장과 창고가 모인 동네였어요. 그렇다고 공장들이 다 떠난 건 아니에요. 지금은 로스터리, 갤러리, 일주일짜리 브랜드 팝업과 골목을 나눠 쓰고 있을 뿐이죠. 붉은 벽돌과 지게차와 플랫화이트가 한데 섞인 풍경, 이게 바로 한국 사람들이 이곳을 "서울의 브루클린"이라고 부르는 이유예요. 가능하면 평일에 오세요. 주말엔 사람이 좀 지나치게 몰리거든요.'},
    route:[
      {time:'10:30', t:{en:'Seongsu stn, exit 2', ja:'聖水駅2番出口', zh:'圣水站2号口', ko:'성수역 2번 출구'},
       d:{en:'Start with brunch at Onion — order the pandoro, trust us.', ja:'まずはOnionでブランチ。パンドーロは必食。', zh:'先去Onion吃早午餐——一定要点Pandoro。', ko:'어니언에서 브런치로 시작. 팡도르는 필수.'}},
      {time:'13:00', t:{en:'Yeonmujang-gil pop-ups', ja:'練武場通りのポップアップ', zh:'练武场街快闪店', ko:'연무장길 팝업'},
       d:{en:'Whatever opened this week — that’s the point of Seongsu.', ja:'今週オープンした店へ。それが聖水の醍醐味。', zh:'看看本周新开了什么——这正是圣水的乐趣。', ko:'이번 주에 뭐가 열렸는지 보는 게 성수의 재미.'}},
      {time:'15:00', t:{en:'Coffee at Daelim Changgo', ja:'大林倉庫でコーヒー', zh:'大林仓库喝咖啡', ko:'대림창고에서 커피'},
       d:{en:'A warehouse-gallery-cafe. The ceiling alone is worth it.', ja:'倉庫×ギャラリー×カフェ。天井だけでも価値あり。', zh:'仓库×画廊×咖啡馆，光看天花板就值了。', ko:'창고이자 갤러리이자 카페. 천장만 봐도 올 만해요.'}},
      {time:'18:00', t:{en:'Gamjatang dinner', ja:'カムジャタンの夕食', zh:'猪骨土豆汤晚餐', ko:'감자탕 저녁'},
       d:{en:'End old-school: pork-bone stew where the factory workers ate.', ja:'締めは昔ながらに、工場で働く人たちが通った店で豚の背骨鍋を。', zh:'用一锅老派的猪骨土豆汤收尾——当年工厂工人吃的就是这一口。', ko:'공장 노동자들이 먹던 그 감자탕으로 마무리.'}},
    ],
    spots:[
      {id:'onion', name:'Onion Seongsu', ko:'어니언 성수', cat:{en:'Bakery cafe', ja:'ベーカリーカフェ', zh:'烘焙咖啡馆', ko:'베이커리 카페'}, price:'₩₩', checked:'2026-09',
       badges:['card','queue'],
       tip:{en:'A 1970s building left largely as it was — it served as a supermarket, diner, home, garage and workshop before the bakery took it over. Two minutes from Seongsu station, exit 2.', ja:'1970年代の建物をそのまま改装。スーパー、食堂、住居、整備工場、町工場として使われてきた建物です。聖水駅2番出口から徒歩2分。', zh:'由1970年代的老建筑改造，此前做过超市、饭馆、住家、汽修厂和工厂。圣水站2号口步行2分钟。', ko:'1970년대 건물을 그대로 살린 공간. 슈퍼마켓, 식당, 가정집, 정비소, 공장으로 쓰이던 자리예요. 성수역 2번 출구에서 도보 2분.'},
       order:{en:'Order at the counter, pay by card, then grab a rooftop seat. Open every day: 08:00–22:00 on weekdays and 09:00–22:00 on weekends, last order 21:30.', ja:'カウンターで注文しカード決済、屋上席へ。平日08:00〜22:00、週末09:00〜22:00（ラストオーダー21:30）、年中無休。', zh:'柜台点单刷卡，然后去天台找座位。平日08:00–22:00，周末09:00–22:00，最后点单21:30，全年无休。', ko:'카운터 주문·카드 결제 후 루프탑 자리로. 평일 08~22시, 주말 09~22시, 라스트오더 21:30, 연중무휴예요.'}},
      {id:'daelim', name:'Daelim Changgo', ko:'대림창고', cat:{en:'Warehouse cafe & gallery', ja:'倉庫カフェ＆ギャラリー', zh:'仓库咖啡馆与画廊', ko:'창고 카페·갤러리'}, price:'₩₩', checked:'2025-06',
       badges:['card'],
       tip:{en:'A 1970s rice mill that became a warehouse in the 1990s — the building people picture when they say “Seongsu warehouse cafe”. What hangs on the walls changes from time to time.', ja:'1970年代は精米所、1990年代からは倉庫だった建物。「聖水の倉庫カフェ」と言われて思い浮かぶ一軒です。壁にかかる展示は時々入れ替わります。', zh:'1970年代是碾米厂，1990年代起用作仓库——说起“圣水仓库咖啡馆”想到的就是这里。墙上的展览会不时更换。', ko:'1970년대엔 정미소, 1990년대부터는 창고였던 건물. "성수 창고 카페" 하면 떠오르는 대표적인 곳이에요. 벽에 걸리는 전시는 수시로 바뀝니다.'},
       order:{en:'Seongsui-ro 78, by Seongsu station exit 3, open 11:00–22:00 daily. A Musinsa store next door carries the Daelim Changgo name as well — the cafe is the building at number 78.', ja:'聖水二路78、聖水駅3番出口すぐ、毎日11:00〜22:00。隣の棟にも「大林倉庫」の名を冠したムシンサのストアがあるので、カフェは78番の建物です。', zh:'圣水二路78号，圣水站3号口附近，每天11:00–22:00。隔壁那栋也挂着“大林仓库”的名字，那是MUSINSA门店，咖啡馆是78号这栋。', ko:'성수이로 78, 성수역 3번 출구 옆이고 매일 11~22시예요. 옆 동에도 같은 이름을 단 무신사 스토어가 있는데, 카페는 성수이로 78 건물이에요.'}},
      {id:'gamjatang', name:'Somunnan Gamjatang', ko:'소문난성수감자탕', cat:{en:'Pork-bone stew, since 1983', ja:'カムジャタン・1983年創業', zh:'猪骨土豆汤老店·1983年开业', ko:'감자탕 노포 · 1983년 창업'}, price:'₩₩', checked:'2026-09',
       badges:['pic_menu','card','late','queue'],
       tip:{en:'The anti-Instagram counterweight to Seongsu — and the best meal on this list.', ja:'映えとは無縁。でもこのリストで一番うまい一皿。', zh:'与网红店相反的存在——却是本清单最好吃的一顿。', ko:'인스타 성수의 반대편. 그리고 이 리스트에서 제일 맛있는 한 끼.'},
       order:{en:'Point to “중” (jung, the medium pot) on the menu — it feeds two. To finish, ask for fried rice: “bokkeumbap!”', ja:'鍋の「中（ジュン）」を指差し注文。2人前です。締めは「ポックンパ！」', zh:'指着菜单点中锅（jung），够两人吃。最后喊一声“bokkeumbap”炒饭收尾。', ko:'"중" 사이즈면 둘이 충분. 마무리는 볶음밥.'}},
      {id:'pov', name:'Point of View', ko:'포인트오브뷰', cat:{en:'Stationery & objects', ja:'文具と道具の店', zh:'文具与生活杂货店', ko:'문구·사물 편집숍'}, price:'₩₩₩', checked:'2026-09',
       badges:['en_menu','card'],
       tip:{en:'A stationery shop staged like a film set. Dangerous for your luggage weight.', ja:'映画のセットのような文具店。荷物の重量制限に注意。', zh:'像电影布景一样的文具店，小心行李超重。', ko:'영화 세트장 같은 문구점. 캐리어 무게 조심.'},
       order:{en:'Three floors — Tool, Scene, Archive. Cards accepted, and many items have descriptions in both Korean and English. Closed on the last Monday of each month.', ja:'1〜3階がTOOL・SCENE・ARCHIVE。カード可、商品説明は韓国語と英語の併記が多いです。毎月最終月曜は休み。', zh:'一到三层分别是TOOL、SCENE、ARCHIVE。可刷卡，不少商品说明韩英对照。每月最后一个周一休息。', ko:'1~3층이 TOOL·SCENE·ARCHIVE. 카드 되고 상품 설명은 한국어·영어가 함께 적힌 게 많아요. 매월 마지막 주 월요일 휴무.'}},
      {id:'lcdc', name:'LCDC Seoul', ko:'엘씨디씨 서울', cat:{en:'Concept store complex', ja:'コンセプトストア複合施設', zh:'概念店综合体', ko:'복합 편집숍'}, price:'₩₩₩', checked:'2026-09',
       badges:['card'],
       tip:{en:'A village of tiny brand rooms stacked inside an old car-repair factory. Start on the top floor and drift down.', ja:'自動車整備工場を改装した、小さなブランドの部屋の集合体。最上階から下りながら巡って。', zh:'旧汽修厂改造的迷你品牌小屋群。从顶层开始往下逛。', ko:'옛 자동차 정비 공장 안에 작은 브랜드 방들이 층층이 들어선 마을 같은 곳. 맨 위층부터 내려오면서 구경하세요.'},
       order:{en:'Each floor is its own world — cafe on the first floor, concept store on the second, six resident brands on the third, brunch on the fourth.', ja:'フロアごとに別世界。1階カフェ、2階セレクトショップ、3階は常設6ブランド、4階はブランチ。', zh:'每层都是另一个世界：一层咖啡、二层买手店、三层六个常驻品牌、四层早午餐。', ko:'층마다 다른 세계예요. 1층 카페, 2층 편집숍, 3층 상설 브랜드 여섯, 4층 브런치.'}},
      {id:'ttukdo', name:'Ttukdo Market', ko:'뚝도시장', cat:{en:'Old neighborhood market', ja:'昔ながらの市場', zh:'老社区市场', ko:'전통시장'}, price:'₩', checked:'2026-09',
       badges:['cash','pic_menu'],
       tip:{en:'The market has stood in its current form since 1962 and has 139 units. Long-running shops sit beside ones opened by young merchants through a 2016–18 youth-merchant program, and as Seongsu’s commercial scene has grown, some units have shuttered and now stand empty.', ja:'1962年から今の形で続く市場で、店舗数は139。2016〜18年の若手商人支援事業で入った店と昔ながらの店が並び、聖水ブームのあおりで空き店舗も出ています。', zh:'1962年起就是现在的格局，共139个摊位。2016至2018年借青年商人扶持项目入驻的新店和老铺并排开着；圣水越来越火，市场里也空出了一些铺位。', ko:'1962년부터 지금 모습으로 이어져 온 시장으로, 점포는 139곳이에요. 2016~18년 청년상인 사업으로 들어온 가게들이 노포와 나란히 있고, 성수 상권이 커지면서 셔터를 내린 빈 점포도 군데군데 생겼어요.'},
       order:{en:'Cash for the old stalls; some of the younger counters take cards.', ja:'昔ながらの店は現金で。若手の店はカードが使えることもあります。', zh:'老摊位备现金；年轻人开的店有些可以刷卡。', ko:'노포는 현금으로, 청년 상인 매대 중엔 카드 되는 곳도 있어요.'}},
    ]
  },

  /* ============ GWANGJANG — full guide ============ */
  {
    id:'gwangjang', tile:'광장', tileClass:'t-gwangjang', full:true, mapArea:'광장시장',
    name:{en:'Gwangjang Market', ja:'広蔵市場', zh:'广藏市场', ko:'광장시장'},
    hangul:'광장시장',
    region:{en:'Jongno, Seoul', ja:'ソウル鍾路', zh:'首尔钟路', ko:'서울 종로'},
    tagline:{
      en:'A 120-year-old market where you eat elbow to elbow with locals.',
      ja:'120年の歴史をもつ市場。地元の人と肩を寄せ合って食べる場所。',
      zh:'120年历史的市场，与本地人肩并肩一起吃。',
      ko:'120년 된 시장. 현지인들과 어깨를 맞대고 먹는 곳.'},
    tags:{en:['Street food','Night','Vintage'], ja:['屋台グルメ','夜','古着'], zh:['街头小吃','夜晚','古着'], ko:['길거리 음식','밤','구제']},
    stats:{station:{en:'Jongno 5-ga, exit 8 (Line 1)', ja:'鍾路5街駅8番出口（1号線）', zh:'钟路5街站8号口（1号线）', ko:'종로5가역 8번 출구 (1호선)'},
           walk:{en:'One covered block', ja:'アーケード1ブロック', zh:'一条带顶棚的街区', ko:'아케이드 한 블록'},
           best:{en:'Tue–Sat, 16:00–21:00', ja:'火〜土 16:00–21:00', zh:'周二至周六 16:00–21:00', ko:'화~토 16–21시'}},
    story:{
      en:'Gwangjang opened in 1905 and never really closed. Under one long roof: silk, hanbok and vintage racks on the floor above, and downstairs the food alley that made it world-famous — mung-bean pancakes fried in cauldrons, gimbap so addictive they call it “narcotic”, raw beef tartare served since your grandparents’ time. Sit on a plastic stool, point, eat. That’s the whole protocol.',
      ja:'1905年開業、以来ほぼ休みなし。ひとつ屋根の下に、2階は絹と韓服と古着、そして1階には世界的に有名になった食の路地。大釜で焼く緑豆チヂミ、「麻薬」と呼ばれる中毒性のキンパ、祖父母の代から続くユッケ。プラスチックの椅子に座り、指差して、食べる。作法はそれだけ。',
      zh:'广藏市场1905年开业，至今几乎从未歇业。同一屋檐下：二楼是丝绸、韩服与古着，楼下则是让它闻名世界的小吃巷——大铁锅里现煎的绿豆煎饼、让人上瘾的“麻药”紫菜包饭、从祖辈那一代就有的生拌牛肉。坐上塑料凳，用手一指，开吃。规矩就这么简单。',
      ko:'1905년에 문을 연 광장시장은 사실상 쉰 적이 없어요. 기다란 한 지붕 아래 2층엔 비단·한복·구제 옷이, 1층엔 이 시장을 세계적으로 유명하게 만든 먹자골목이 있죠. 가마솥에서 부치는 빈대떡, 마약이라 불릴 만큼 당기는 김밥, 조부모 세대부터 이어진 육회까지. 플라스틱 의자에 앉아서, 손으로 가리키고, 먹으면 돼요. 규칙은 그게 전부예요.'},
    route:[
      {time:'16:00', t:{en:'Vintage floor first', ja:'まずは古着フロアへ', zh:'先上古着楼层', ko:'구제상가 먼저'},
       d:{en:'The vintage floor closes at 7pm and is shut on Sundays, and the tartare shop is closed on Mondays — so this route works Tuesday to Saturday.', ja:'古着フロアは19時閉店・日曜休み。ユッケの店は月曜休みなので、このコースは火〜土向けです。', zh:'古着楼层七点关门、周日休息；生拌牛肉店周一休息——所以这条线适合周二到周六。', ko:'구제상가는 19시에 닫고 일요일엔 쉬어요. 육회집은 월요일 휴무라 이 코스는 화~토에만 맞아요.'}},
      {time:'17:00', t:{en:'Bindaetteok at Sunhui-ne', ja:'スニネでピンデトク', zh:'在顺姬家吃绿豆煎饼', ko:'순희네 빈대떡'},
       d:{en:'Mung beans ground in a stone mill and fried to order — with a bottle of makgeolli.', ja:'石臼で挽いた緑豆をその場で焼いてくれます。マッコリを一本添えて。', zh:'石磨现磨绿豆、现煎现吃，再来一瓶米酒。', ko:'맷돌로 간 녹두를 바로 부쳐 줍니다. 막걸리 한 병 곁들여서.'}},
      {time:'18:00', t:{en:'Mini gimbap', ja:'ミニキンパ', zh:'迷你紫菜包饭', ko:'꼬마김밥'},
       d:{en:'A roll is ₩4,000 — dip it in the mustard-soy sauce. Monyeo Gimbap’s Dongho-ro stall stays open later than the one in the covered alley.', ja:'1本₩4,000、からし醤油につけて。モニョキンパ（모녀김밥）は東湖路側の店の方が、アーケード内の店より遅くまで開いています。', zh:'一条₩4,000，蘸芥末酱油吃。Monyeo Gimbap（모녀김밥）东湖路那家比市场顶棚下那家关得晚。', ko:'한 줄 4,000원, 겨자 간장에 찍어서. 모녀김밥은 동호로 쪽 가게가 시장 안 가게보다 늦게까지 해요.'}},
      {time:'18:45', t:{en:'Yukhoe alley', ja:'ユッケ横丁', zh:'生拌牛肉巷', ko:'육회골목'},
       d:{en:'Beef tartare with egg yolk and shredded pear, ₩23,000 at the sisters’ shop that opened in 1974.', ja:'卵黄と梨の千切りをのせたユッケ、1974年創業の姉妹の店で₩23,000。', zh:'配蛋黄和梨丝的生拌牛肉₩23,000，就在1974年由两姐妹开的那家店。', ko:'노른자와 배채 올린 육회 23,000원. 1974년에 연 자매의 가게에서.'}},
    ],
    spots:[
      {id:'sunhui', name:'Sunhui-ne Bindaetteok', ko:'순희네 빈대떡', cat:{en:'Mung-bean pancake', ja:'緑豆チヂミ', zh:'绿豆煎饼', ko:'빈대떡'}, price:'₩', checked:'2026-09',
       badges:['pic_menu','card','queue'],
       tip:{en:'Watch them grind the beans in the stone mill while you queue.', ja:'行列中は石臼で豆を挽く様子を見物。', zh:'排队时可以看石磨现磨绿豆。', ko:'줄 서는 동안 맷돌로 녹두 가는 걸 구경하세요.'},
       order:{en:'One pancake and one bottle of makgeolli per two people. Sharing a table with strangers is normal.', ja:'2人でチヂミ1枚＋マッコリ1本。相席が普通です。', zh:'两人一张饼一瓶米酒。拼桌很正常。', ko:'2인당 빈대떡 하나, 막걸리 한 병. 합석은 기본.'}},
      {id:'mayak', name:'Monyeo Gimbap', ko:'모녀김밥', cat:{en:'Mini gimbap stall', ja:'ミニキンパ屋台', zh:'迷你紫菜包饭摊', ko:'꼬마김밥'}, price:'₩', checked:'2026-09',
       badges:['pic_menu','cash'],
       tip:{en:'The “mayak” nickname came from a sauce people call addictive. In 2024 the market’s merchants voted the word off their signboards — they now read kkoma (mini) or wonjo (original) gimbap — though some English menus still print it.', ja:'「麻薬」の名は、後を引くタレの中毒性から。2024年に商人会が看板からこの言葉を外すことを決め、今は「コマ（ミニ）キンパ」「元祖キンパ」などの表記です。ただ英語メニューには今も残っていることがあります。', zh:'“麻药”这个外号来自那种让人停不下来的酱汁。2024年市场商人会决定把这两个字从招牌上拿掉，现在写的是迷你紫菜包饭（꼬마김밥）或元祖紫菜包饭（원조김밥）——不过有些英文菜单上还印着这个词。', ko:'"마약"은 자꾸 당기는 소스 맛에서 온 별명이에요. 2024년 상인회 결의로 간판에서는 이 말을 뺐고 지금은 꼬마김밥·원조김밥으로 적습니다. 영어 메뉴에는 아직 남아 있는 곳도 있어요.'},
       order:{en:'Hold up fingers for plates. Dip in the mustard-soy sauce.', ja:'指で皿数を伝え、からし醤油につけて。', zh:'用手指比划要几盘，蘸芥末酱油吃。', ko:'접시 수는 손가락으로, 소스는 겨자 간장에.'}},
      {id:'jamae', name:'Yukhoe Jamae-jip', ko:'육회자매집', cat:{en:'Beef tartare (yukhoe)', ja:'ユッケ専門', zh:'生拌牛肉', ko:'육회'}, price:'₩₩', checked:'2026-09',
       badges:['pic_menu','card'],
       tip:{en:'Two sisters opened it in 1974 — jamae means “sisters”. Still a family shop in the tartare alley.', ja:'1974年に姉妹が始めた店。「チャメ」は姉妹の意味です。今も家族で続けるユッケ横丁の一軒。', zh:'1974年由两姐妹开的店，“자매”就是姐妹的意思。至今仍是生拌牛肉巷里的家族小店。', ko:'1974년 두 자매가 연 집. 지금도 육회골목에서 가족이 이어 가고 있어요.'},
       order:{en:'Order the basic yukhoe, topped with raw egg yolk and pear. Add yuk-sashimi (sliced raw beef) if you’re brave.', ja:'卵黄と梨がのった基本のユッケを。勇気があれば「ユッサシミ（生の牛肉の刺身）」も追加で。', zh:'点配蛋黄和梨丝的基本款，胆大可加“生牛肉片”。', ko:'기본 육회에, 용감하다면 육사시미 추가.'}},
      {id:'kalguksu', name:'Gohyang Kalguksu', ko:'고향칼국수', cat:{en:'Hand-cut noodles', ja:'手打ちカルグクス', zh:'手擀刀切面', ko:'칼국수'}, price:'₩', checked:'2026-09',
       badges:['pic_menu','card','queue'],
       tip:{en:'The grandmother’s hand-cut noodle counter inside the market — the one from the Netflix documentary “Street Food”. Foreign visitors have been finding it ever since, so expect a line.', ja:'市場の中にある、おばあちゃんの手打ちカルグクスの店。Netflixのドキュメンタリー「ストリート・グルメを求めて」に登場した一軒で、それ以来海外からの客が増えて行列ができます。', zh:'市场里那家奶奶的手擀刀切面摊——就是Netflix纪录片《Street Food》拍过的那家。之后外国客人变多，常常要排队。', ko:'시장 안 할머니 칼국수 좌판. 넷플릭스 「길 위의 셰프들」에 나온 그 집이에요. 그 뒤로 외국인 손님이 늘어 줄이 섭니다.'},
       order:{en:'Anchovy-broth hand-cut noodles, with kimchi on the side.', ja:'煮干しだしの手打ちカルグクスに、キムチが添えられます。', zh:'用小鳀鱼高汤煮的手擀刀切面，配一碟泡菜。', ko:'멸치육수 칼국수에 김치가 함께 나옵니다.'}},
      {id:'sikhye', name:'Sikhye & Sujeonggwa Stand', ko:'식혜·수정과 좌판', cat:{en:'Traditional sweet drinks', ja:'伝統甘味ドリンク', zh:'传统甜饮', ko:'전통 음료'}, price:'₩',
       badges:['cash','veg'],
       tip:{en:'The palate cleanser between fried rounds — ice-cold rice punch or cinnamon punch.', ja:'チヂミや揚げ物の合間の口直しに。キンキンに冷えたシッケ（甘い米の飲み物）か、シナモン風味のスジョングァを。', zh:'一轮轮煎饼、炸物吃下来，中间清清口——冰镇甜米露或肉桂水。', ko:'전이나 튀김 사이사이 입가심으로. 차가운 식혜나 수정과.'},
       order:{en:'Point at the milky one (sikhye) or the amber one (sujeonggwa) — prices vary from stall to stall.', ja:'白い方がシッケ、琥珀色がスジョングァ。値段は屋台ごとに違います。', zh:'奶白色是甜米露，琥珀色是肉桂水，价格各摊不同。', ko:'뽀얀 쪽이 식혜, 갈색이 수정과. 가격은 좌판마다 달라요.'}},
      {id:'vintage', name:'Gwangjang Vintage', ko:'광장시장 구제상가', cat:{en:'Vintage clothing floor', ja:'古着フロア', zh:'古着楼层', ko:'구제상가'}, price:'₩₩', checked:'2026-09',
       badges:['cash'],
       tip:{en:'Second floor — take the stairs past the “수입구제” (imported vintage) sign. It closes at 7pm and is shut on Sundays. There are far fewer shops than there used to be, and some sellers now open just one day a week.', ja:'2階。「수입구제（輸入古着）」の看板の先の階段を上ります。19時閉店・日曜休み。店舗数はかなり減り、週に一日しか開けない店もあります。', zh:'在二层，沿着写有“수입구제（进口古着）”的招牌上楼。七点关门、周日休息。摊位少了很多，有的卖家一周只开一天。', ko:'"수입구제" 간판을 지나 계단으로 2층. 19시에 닫고 일요일은 휴무예요. 점포가 많이 줄어서 일주일에 하루만 여는 가게도 있습니다.'},
       order:{en:'Cash is the safe bet up here. Friendly haggling is fine; rudeness is not.', ja:'この階は現金があると安心。値切りはOK、無礼はNG。', zh:'楼上最好带现金。可以友好砍价，但别失礼。', ko:'위층에선 현금이 제일 무난해요. 기분 좋게 흥정하는 건 괜찮지만, 무례하게 굴면 안 돼요.'}},
    ]
  },

  /* ============ EULJIRO — full guide ============ */
  {
    id:'euljiro', tile:'을지로', tileClass:'t-euljiro', full:true, mapArea:'을지로3가',
    name:{en:'Euljiro', ja:'乙支路（ウルチロ）', zh:'乙支路', ko:'을지로'},
    hangul:'을지로 · 힙지로',
    region:{en:'Central Seoul', ja:'ソウル中心部', zh:'首尔市中心', ko:'서울 중구'},
    tagline:{
      en:'Print shops by day, hidden bars up unmarked staircases by night.',
      ja:'昼は印刷所、夜は看板のない階段の先のバーへ。',
      zh:'白天是印刷厂，夜晚是无名楼梯尽头的酒吧。',
      ko:'낮엔 인쇄소, 밤엔 간판 없는 계단 위의 바.'},
    tags:{en:['Bars','Retro','After dark'], ja:['バー','レトロ','夜'], zh:['酒吧','复古','夜生活'], ko:['바','레트로','밤']},
    stats:{station:{en:'Euljiro 3-ga (Line 2/3)', ja:'乙支路3街駅（2・3号線）', zh:'乙支路3街站（2/3号线）', ko:'을지로3가역 (2·3호선)'},
           walk:{en:'~15 min radius', ja:'徒歩約15分圏', zh:'约15分钟范围', ko:'도보 15분 반경'},
           best:{en:'18:00–late', ja:'18:00〜深夜', zh:'18:00至深夜', ko:'18시–심야'}},
    story:{
      en:'Euljiro is Seoul’s workshop — printing presses, tile merchants, lighting shops. When rents rose elsewhere, young bartenders and artists moved into the upper floors, changed nothing about the staircases, and put a bar behind a steel door. Locals nicknamed it “Hipjiro”. Half the fun is not being sure you’re in the right building.',
      ja:'乙支路はソウルの町工場街。印刷所、タイル問屋、照明店が軒を連ねます。よその家賃が上がると、若いバーテンダーやアーティストがビルの上の階に入り、階段には手を付けず、鉄の扉の奥にバーを開きました。地元の人がつけたあだ名は「ヒップチロ」。「このビルで合ってる？」と迷うのも楽しみのうちです。',
      zh:'乙支路是首尔的车间——印刷机、瓷砖行、灯具店。别处租金上涨后，年轻的调酒师和艺术家搬进了楼上，楼梯原封不动，在铁门后开起了酒吧。本地人给它起了个外号叫“Hip支路”（힙지로）。乐趣有一半就在于：你总不太确定自己是不是进对了楼。',
      ko:'을지로는 서울의 작업장 같은 곳이에요. 인쇄소, 타일 가게, 조명 상가가 모여 있죠. 다른 동네 임대료가 오르자 젊은 바텐더와 예술가들이 건물 위층으로 들어왔고, 계단은 그대로 둔 채 철문 뒤에 바를 열었어요. 동네 사람들이 붙인 별명은 힙지로. 제대로 찾아온 건물인지 긴가민가한 것까지가 재미예요.'},
    route:[
      {time:'15:30', t:{en:'Ssanghwa-cha at Eulji Dabang', ja:'乙支茶房でサンファ茶', zh:'乙支茶房的双和茶', ko:'을지다방 쌍화차'},
       d:{en:'A coffee room open since 1985. Redevelopment moved it across the street in 2022, and the whole interior — BTS photos included — came along. Order the herbal tea with the egg yolk.', ja:'1985年から続く喫茶室。2022年の再開発で向かいの建物へ移り、BTSの写真を含め店内をそのまま運びました。卵黄入りの韓方茶を。', zh:'1985年开到现在的老咖啡室。2022年因旧城改造搬到了街对面的楼里，店内陈设连同BTS的照片都原样带了过去。点那杯加蛋黄的双和茶。', ko:'1985년부터 이어온 다방. 2022년 재개발로 건너편 건물로 옮기면서 BTS 사진까지 내부를 그대로 가져왔어요. 노른자 동동 쌍화차 한 잔.'}},
      {time:'17:00', t:{en:'Print-alley wander', ja:'印刷路地さんぽ', zh:'印刷巷漫步', ko:'인쇄골목 산책'},
       d:{en:'Watch the presses wind down as the steel shutters come up on the bars.', ja:'印刷機が止まる頃、バーのシャッターが開き始めます。', zh:'看印刷机收工，酒吧的铁门渐次拉开。', ko:'인쇄기가 멈출 무렵, 바들의 철문이 하나둘 열립니다.'}},
      {time:'18:30', t:{en:'First round: Nogari Alley', ja:'一次会はノガリ横丁', zh:'第一轮：明太鱼干巷', ko:'1차: 노가리골목'},
       d:{en:'Cold draft + dried pollack on a plastic stool. Summer’s best seat in Seoul.', ja:'プラ椅子で生ビールと干しダラ。ソウルの夏の特等席。', zh:'塑料凳上冰生啤配鱼干，首尔夏夜最佳座位。', ko:'플라스틱 의자에서 생맥주와 노가리. 서울 여름의 명당.'}},
      {time:'20:30', t:{en:'Second round: golbaengi', ja:'二次会はコルベンイ', zh:'第二轮：辣拌海螺', ko:'2차: 골뱅이'},
       d:{en:'Spicy whelk salad, egg roll, and the night is officially on.', ja:'ピリ辛つぶ貝と卵焼きで、夜はここから本番。', zh:'辣拌海螺加韩式煎蛋卷，夜晚正式开场。', ko:'골뱅이무침에 계란말이. 밤은 이제부터 시작.'}},
    ],
    spots:[
      {id:'nogari', name:'Nogari Alley', ko:'을지로 노가리골목', cat:{en:'Open-air beer alley', ja:'路上ビール横丁', zh:'露天啤酒巷', ko:'노가리 골목'}, price:'₩', checked:'2026-09',
       badges:['pic_menu','card','late'],
       tip:{en:'Come evening, hundreds of drinkers fill plastic tables in the open air. Dried pollack and cold draft beer are still the core order, though fried chicken and stews are on the menu now. Street seating depends on the district office’s permits, so on some nights it isn’t set out.', ja:'夜になると路上のプラ席に数百人。基本は干しダラと生ビール、今はチキンや鍋ものもあります。ただ路上営業は区の許可次第で、出ていない日もあります。', zh:'入夜后露天塑料桌前坐着数百人。基本款还是明太鱼干配冰生啤，如今也添了炸鸡和汤锅——不过路边摆桌要看区厅的许可，有时并不摆。', ko:'저녁이면 길가 플라스틱 테이블에 수백 명이 모여요. 기본은 노가리에 생맥주이고, 요즘은 치킨과 탕 안주도 있어요. 다만 야외 테이블은 구청 허가에 달려 있어서 안 깔리는 날도 있어요.'},
       order:{en:'Sit anywhere, call out “saeng-maekju!” (draft beer), then point at the fish on the next table.', ja:'座って「センメクチュ！」と一声。隣の干物を指差せば通じます。', zh:'随便坐下喊“saeng-maekju”（生啤），再指指邻桌的鱼干。', ko:'아무 데나 앉아 "생맥주!" 그리고 옆 테이블 노가리를 가리키면 됩니다.'}},
      {id:'manseon', name:'Manseon Hof', ko:'만선호프', cat:{en:'Beer hall on Nogari Alley, since 2014', ja:'ノガリ横丁のビヤホール・2014年開業', zh:'明太鱼干巷的啤酒馆 2014年开业', ko:'노가리골목 호프 · 2014년 1호점'}, price:'₩', checked:'2026-09',
       badges:['pic_menu','card','late','queue'],
       tip:{en:'A latecomer that opened here in 2014 and now runs about ten branches along the same alley. Fried chicken gizzards are the insider order.', ja:'2014年にこの横丁へ来た後発組で、今は同じ通りに10軒ほどの支店があります。通は砂肝の唐揚げを頼みます。', zh:'2014年才进这条巷子的后来者，如今在同一条街上开了十来家分店。行家点的是炸鸡胗。', ko:'2014년에 이 골목에 들어온 후발 주자인데, 지금은 같은 골목에 지점이 열 곳 남짓이에요. 아는 사람은 닭똥집 튀김.'},
       order:{en:'Beer comes in 500cc glasses. Order food by pointing at the wall menu photos.', ja:'ビールは500cc。壁の写真メニューを指差し注文。', zh:'啤酒论500cc卖，看墙上照片菜单指着点。', ko:'맥주는 500cc, 안주는 벽 사진 메뉴로.'}},
      {id:'hanyakbang', name:'Coffee Hanyakbang', ko:'커피한약방', cat:{en:'Hidden alley cafe', ja:'路地裏のカフェ', zh:'巷弄深处的咖啡馆', ko:'골목 카페'}, price:'₩₩', checked:'2026-09',
       badges:['card'],
       tip:{en:'Down an alley barely one person wide. Antique cabinets from an old herbal pharmacy.', ja:'人ひとり分の路地の奥。韓方薬局の古箪笥がそのまま。', zh:'藏在仅容一人通过的窄巷深处，摆着老韩药房的古董柜。', ko:'한 사람 겨우 지나는 골목 끝. 한약방 고가구가 그대로.'},
       order:{en:'Filter coffee is the house style, but espresso, latte and cappuccino are on the menu too.', ja:'看板はフィルターコーヒー（ハンドドリップ）ですが、エスプレッソ・カフェラテ・カプチーノもあります。', zh:'招牌是手冲滤泡咖啡，不过菜单上也有意式浓缩、拿铁和卡布奇诺。', ko:'대표 메뉴는 필터커피(핸드드립)이지만 에스프레소·라떼·카푸치노도 있어요.'}},
      {id:'dabang', name:'Eulji Dabang', ko:'을지다방', cat:{en:'Retro coffee room, est. 1985', ja:'レトロ喫茶・1985年創業', zh:'复古咖啡室 1985年开业', ko:'레트로 다방 · 1985년 개업'}, price:'₩', checked:'2026-09',
       badges:['pic_menu','cash'],
       tip:{en:'Vinyl seats, wall fans, and ssanghwa-cha — a herbal tonic tea crowned with an egg yolk. Time travel for ₩6,000.', ja:'ビニールソファ、壁掛け扇風機、卵黄入りのサンファ茶。₩6,000のタイムトラベル。', zh:'人造革沙发、壁挂风扇，还有加了蛋黄的双和茶（一种滋补药草茶）——₩6,000的时光旅行。', ko:'비닐 소파와 벽걸이 선풍기, 노른자 쌍화차. 6천원짜리 시간여행.'},
       order:{en:'Opens early — from around 6am on weekdays — and stays open into the evening. The ramyeon-and-rice set (₩4,000) is served only until 11am.', ja:'朝が早く、平日は6時ごろから夜まで開いています。ラミョン（韓国のラーメン）とごはんのセット（₩4,000）は午前11時まで。', zh:'开得很早，工作日从早上六点左右一直开到晚上。拉面加饭（₩4,000）只卖到上午11点。', ko:'아침 일찍 열어요. 평일은 6시쯤부터 저녁까지 합니다. 라면에 밥(4,000원)은 오전 11시까지만.'}},
      {id:'golbaengi', name:'Golbaengi Alley', ko:'을지로 골뱅이골목', cat:{en:'Spicy whelk alley', ja:'つぶ貝横丁', zh:'辣拌海螺巷', ko:'골뱅이 골목'}, price:'₩₩', checked:'2026-09',
       badges:['pic_menu','card','late'],
       tip:{en:'Euljiro’s other alley: sea-snail salad in fire-red sauce that demands cold beer.', ja:'乙支路のもう一つの横丁。真っ赤なタレで和えたつぶ貝には、冷えたビールが欠かせません。', zh:'乙支路的另一条巷子：火红酱汁拌海螺，必须配冰啤酒。', ko:'을지로의 또 다른 골목. 새빨간 양념 골뱅이엔 찬 맥주가 국룰.'},
       order:{en:'Order the golbaengi-muchim. At many places an egg roll and a fish-cake soup arrive with it on the house, so there is no need to order those.', ja:'頼むのはつぶ貝和え。多くの店では卵焼きとおでんスープがサービスで付いてくるので、別に注文する必要はありません。', zh:'点一份拌海螺就好。很多店家会免费送上韩式煎蛋卷和鱼饼汤，不用另外点。', ko:'골뱅이무침만 시키면 돼요. 많은 집에서 계란말이와 오뎅탕이 서비스로 나와서 따로 주문할 필요가 없습니다.'}},
    ]
  },

  /* ============ MANGWON — preview ============ */
  {
    id:'mangwon', tile:'망원', tileClass:'t-mangwon', full:true, mapArea:'망원동',
    name:{en:'Mangwon', ja:'望遠（マンウォン）', zh:'望远洞', ko:'망원'},
    hangul:'망원동',
    region:{en:'West Seoul', ja:'ソウル西部', zh:'首尔西部', ko:'서울 서부'},
    tagline:{
      en:'A real neighborhood market, then a picnic on the Han River.',
      ja:'生活感ある市場を歩き、漢江でピクニックを。',
      zh:'逛完真实的社区市场，去汉江野餐。',
      ko:'진짜 동네 시장 구경 후, 한강 피크닉.'},
    tags:{en:['Market','River','Low-key'], ja:['市場','漢江','ローカル'], zh:['市场','汉江','低调'], ko:['시장','한강','로컬']},
    stats:{station:{en:'Mangwon (Line 6)', ja:'望遠駅（6号線）', zh:'望远站（6号线）', ko:'망원역 (6호선)'},
           walk:{en:'Market → river: 15 min', ja:'市場→漢江 徒歩15分', zh:'市场→江边15分钟', ko:'시장→한강 15분'},
           best:{en:'15:00–sunset', ja:'15:00〜日没', zh:'15:00至日落', ko:'15시–일몰'}},
    story:{
      en:'Mangwon is what Hongdae was before the tour buses: a working market street where grandmothers shop next to film students. The move is simple and perfect — graze through Mangwon Market (croquettes, tteokbokki, cups of dakgangjeong), buy a mat at a convenience store, and walk fifteen minutes to Mangwon Hangang Park for sunset over the river.',
      ja:'望遠は、観光バスが押し寄せる前の弘大のような町。おばあちゃんと映画専攻の学生が並んで買い物をする、暮らしの市場通りです。過ごし方はシンプル。望遠市場で食べ歩き（コロッケ、トッポッキ、カップ入りのタッカンジョン）、コンビニでレジャーシートを買い、15分歩いて望遠漢江公園へ。あとは川に沈む夕日を待つだけです。',
      zh:'望远洞是旅游大巴到来之前的弘大：奶奶们和电影学生并肩买菜的市场街。玩法简单而完美——在望远市场边走边吃（可乐饼、炒年糕、一杯甜脆炸鸡），在便利店买张野餐垫，步行十五分钟到望远汉江公园看日落。',
      ko:'망원은 관광버스가 오기 전의 홍대 같은 곳이에요. 할머니와 영화과 학생이 나란히 장을 보는 시장 동네죠. 코스는 간단하고 완벽해요. 망원시장에서 고로케·떡볶이·컵 닭강정을 사 먹으며 돌고, 편의점에서 돗자리를 산 다음, 15분 걸어 망원한강공원에서 강 위로 지는 노을을 보면 돼요.'},
    route:[
      {time:'14:00', t:{en:'Start at Ugly Bakery', ja:'アグリーベーカリーから', zh:'从Ugly Bakery出发', ko:'어글리베이커리부터'},
       d:{en:'It opens at noon and is closed Mondays and Tuesdays, so this walk works Wednesday to Sunday. Take the spring-onion bread with you.', ja:'12時オープン、月・火は休み。つまりこの散歩は水〜日向けです。大葱パンを持って出発。', zh:'中午12点开门，周一周二休息，所以这条线适合周三到周日。带上大葱面包再走。', ko:'12시에 열고 월·화는 쉽니다. 그래서 이 코스는 수~일 기준이에요. 대파빵을 챙겨 출발.'}},
      {time:'15:00', t:{en:'Graze Mangwon Market', ja:'望遠市場を食べ歩く', zh:'在望远市场边走边吃', ko:'망원시장 한 바퀴'},
       d:{en:'Sit down for ₩4,000 noodles at Gohyangjip, then take a ₩5,000 cup of dakgangjeong from Q’s for later.', ja:'コヒャンジプで₩4,000のカルグクスを座って食べ、キューズのタッカンジョン（カップ₩5,000）は持ち帰り用に。', zh:'在Gohyangjip（고향집）坐下吃一碗₩4,000的刀切面，再从Q’s打包一杯₩5,000的甜脆炸鸡。', ko:'고향집에서 4,000원 칼국수로 한 끼, 큐스닭강정 컵 5,000원은 들고 나가기.'}},
      {time:'16:30', t:{en:'Board the Seoul Battleship', ja:'ソウル艦公園へ', zh:'登上首尔舰', ko:'서울함공원 승선'},
       d:{en:'About fifteen minutes on foot to the riverside, then a little further west along the park. ₩3,000 puts you inside a frigate, a patrol boat and a submarine. Closed Mondays.', ja:'市場から川辺まで徒歩約15分、そこから公園沿いに少し西へ。₩3,000で護衛艦・高速艇・潜水艦の中へ。月曜休館。', zh:'从市场步行约十五分钟到江边，再沿着公园往西走一段。₩3,000就能走进护卫舰、高速艇和潜艇。周一闭馆。', ko:'시장에서 강변까지 걸어서 15분쯤, 거기서 공원을 따라 조금 더 서쪽으로. 3,000원이면 호위함·고속정·잠수함 안까지 들어갑니다. 월요일 휴관.'}},
      {time:'18:00', t:{en:'Sunset at Mangwon Hangang Park', ja:'望遠漢江公園で夕日', zh:'望远汉江公园看日落', ko:'망원한강공원에서 노을'},
       d:{en:'Buy a mat at the convenience store, boil ramyeon in the machine, and let the river turn orange.', ja:'コンビニでシートを買い、ラーメン調理機で一杯。川がオレンジに染まるのを待ちます。', zh:'在便利店买张野餐垫，用煮面机煮碗拉面，等江面染成橙色。', ko:'편의점에서 돗자리 사고, 라면 조리기에 한 그릇. 강이 주황으로 물드는 걸 봅니다.'}},
    ],
    spots:[
      {id:'market', name:'Mangwon Market', ko:'망원시장', cat:{en:'Covered market street', ja:'アーケード市場', zh:'带顶棚的市场街', ko:'전통시장'}, price:'₩', checked:'2026-09',
       badges:['card','cash','pic_menu','veg'],
       tip:{en:'Eat in laps: croquette → tteokbokki → kalguksu → hotteok. ₩10,000 covers it all.', ja:'コロッケ→トッポッキ→カルグクス→ホットク。1万ウォンで一周できます。', zh:'按圈吃：可乐饼→炒年糕→刀切面→糖饼，一万韩元全搞定。', ko:'고로케→떡볶이→칼국수→호떡. 만 원이면 한 바퀴.'},
       order:{en:'Most stalls take cards and phone pay now; keep a few small bills for the ones that don’t. Point at what you want.', ja:'今はほとんどの店でカードやスマホ決済が使えます。使えない店のために小額紙幣を少しだけ。注文は指差しでOK。', zh:'如今大多数摊位可以刷卡或手机支付，只为少数不收卡的摊位备点零钱。指一指就能点。', ko:'요즘은 대부분 카드·간편결제가 됩니다. 안 되는 곳을 위해 잔돈만 조금. 주문은 가리키면 끝.'}},
      {id:'gohyangjip', name:'Gohyangjip', ko:'고향집', cat:{en:'Hand-cut noodles in the market', ja:'市場の手打ち麺食堂', zh:'市场里的手擀面馆', ko:'시장 칼국수집'}, price:'₩', checked:'2026-09',
       badges:[],
       tip:{en:'Hand-cut noodles for ₩4,000 in the middle of the market — a certified “fair price” shop that Korean television keeps coming back to.', ja:'市場のど真ん中でカルグクス₩4,000。「良心価格店」に指定され、韓国のテレビ番組が何度も訪れている店です。', zh:'就在市场正中，刀切面₩4,000。被认定为“良心价格店”，韩国电视节目一再造访。', ko:'시장 한복판의 4,000원짜리 칼국수. 착한가격업소로 지정됐고, 방송에도 여러 번 나왔어요.'},
       order:{en:'Open 10:00–21:00, last order 20:30, no afternoon break. Everything can be packed to go. On maps, search “고향집 망원시장” — the name alone brings up half of Seoul.', ja:'10:00〜21:00、ラストオーダー20:30、中休みなし。全メニュー持ち帰り可。地図では同名店が多いので「고향집 망원시장」で検索を。', zh:'10:00–21:00营业，最后点单20:30，中间不休息。全部菜品可打包。地图上请搜“고향집 망원시장”，同名店太多。', ko:'10~21시, 라스트오더 20:30, 브레이크타임 없음. 전 메뉴 포장 가능. 지도에선 "고향집 망원시장"으로 검색하세요.'}},
      {id:'qsdakgangjeong', name:'Q’s Dakgangjeong', ko:'큐스닭강정', cat:{en:'Sweet-crisp fried chicken', ja:'甘辛フライドチキン', zh:'甜脆炸鸡', ko:'닭강정'}, price:'₩', checked:'2026-09',
       badges:['card','queue'],
       tip:{en:'A ₩5,000 cup is enough to taste the sauces — original, sweet soy, green chili mayo, cream, cheese. The line here is usually one of the longer ones in the market.', ja:'₩5,000のカップひとつで味の食べ比べができます（オリジナル、甘辛醤油、青唐辛子マヨ、クリーム、チーズ）。市場でもよく並ぶ店です。', zh:'一杯₩5,000就够试味道：原味、甜酱油、青阳辣椒蛋黄酱、奶油、芝士。在市场里通常算是排队比较长的一家。', ko:'5,000원짜리 컵 하나로 소스 맛보기 충분해요. 오리지널·간장·청양마요·크림·치즈. 시장에서 줄이 긴 편이에요.'},
       order:{en:'Open 09:30–20:30 daily; cards and phone pay are fine. Bigger boxes run from ₩10,000 for half a bird in two sauces up to ₩25,000 for two birds in five.', ja:'毎日09:30〜20:30、カード・スマホ決済可。大きいサイズは、半羽で2種類の味の₩10,000から、2羽で5種類の味の₩25,000まで。', zh:'每天09:30–20:30，可刷卡与手机支付。大份从两种口味半只₩10,000，到五种口味两只₩25,000。', ko:'매일 09:30~20:30, 카드·간편결제 됩니다. 큰 사이즈는 반마리 두 가지 맛 1만 원부터, 두 마리 다섯 가지 맛 2만 5천 원까지.'}},
      {id:'uglybakery', name:'Ugly Bakery', ko:'어글리베이커리', cat:{en:'Backstreet bakery', ja:'路地のベーカリー', zh:'小巷面包店', ko:'동네 베이커리'}, price:'₩', checked:'2026-09',
       badges:['queue'],
       tip:{en:'The spring-onion bread is what the line is for, with a matcha mammoth loaf close behind. Closed Mondays and Tuesdays.', ja:'行列の理由は大葱パン。抹茶マンモスパンも人気です。月・火は休み。', zh:'排队都是为了大葱面包，抹茶猛犸面包紧随其后。周一、周二休息。', ko:'줄 서는 이유는 대파빵, 그다음은 말차 맘모스. 월·화요일은 휴무예요.'},
       order:{en:'Opens at noon. Take it away for the river — a cool bag is ₩1,500 extra. No parking.', ja:'12時オープン。漢江に持っていくなら保冷バッグ₩1,500。駐車場はありません。', zh:'中午12点开门。要带去江边的话，保冷袋另加₩1,500。没有停车位。', ko:'12시에 엽니다. 한강까지 들고 갈 거면 보냉백 1,500원. 주차는 안 돼요.'}},
      {id:'battleship', name:'Seoul Battleship Park', ko:'서울함공원', cat:{en:'Retired warships you can board', ja:'退役軍艦の公園', zh:'退役军舰公园', ko:'퇴역 함정 공원'}, price:'₩', checked:'2026-09',
       badges:[],
       tip:{en:'You can walk through a 102-meter frigate that served for thirty years, plus a patrol boat and a submarine — all inside Mangwon Hangang Park.', ja:'30年間就役した全長102mの護衛艦の中を歩けます。高速艇と潜水艦も。すべて望遠漢江公園の中にあります。', zh:'可以走进一艘服役三十年、长102米的护卫舰，还有高速艇和潜艇——全都在望远汉江公园里。', ko:'30년을 운용한 102m 호위함 안을 걸어 다닐 수 있어요. 고속정과 잠수함까지, 전부 망원한강공원 안에 있습니다.'},
       order:{en:'₩3,000 for adults, ₩1,000 for children. Closed Mondays. From March to October it’s open 10:00–19:00 Tuesday to Friday and until 20:00 on weekends; last entry is 30 minutes before closing.', ja:'大人₩3,000、子ども₩1,000。月曜休館。3〜10月は火〜金10:00〜19:00、土日は20:00まで（入場は閉館30分前まで）。', zh:'成人₩3,000，儿童₩1,000。周一闭馆。3至10月周二至周五10:00–19:00，周末至20:00，闭馆前30分钟停止入场。', ko:'성인 3,000원, 어린이 1,000원. 월요일 휴관. 3~10월은 화~금 10~19시, 주말은 20시까지이고 입장 마감은 30분 전입니다.'}},
      {id:'hangang', name:'Mangwon Hangang Park', ko:'망원한강공원', cat:{en:'Riverside park', ja:'漢江公園', zh:'汉江公园', ko:'한강공원'}, price:'FREE', checked:'2026-09',
       badges:['late','veg'],
       tip:{en:'Delivery does not come to your mat — you collect it yourself at the delivery zone by the Mangwon entrance gate.', ja:'出前はシートまでは来ません。望遠ナドゥルモク（入口）近くの指定デリバリーゾーンで自分で受け取ります。', zh:'外卖不会送到野餐垫，要自己去望远入口附近的指定取餐区领。', ko:'배달은 돗자리까지 오지 않아요. 망원나들목 근처 지정 배달존에서 직접 받습니다.'},
       order:{en:'Convenience-store ramyeon machines at the park store. Try it once.', ja:'園内コンビニのラーメン調理機は一度試す価値あり。', zh:'公园便利店的煮面机值得一试。', ko:'편의점 라면 조리기는 한 번쯤 경험해 보세요.'}},
    ]
  },

  /* ============ GANGNEUNG — preview ============ */
  {
    id:'gangneung', tile:'명주', tileClass:'t-gangneung', full:true, mapArea:'강릉 명주동',
    name:{en:'Gangneung Myeongju-dong', ja:'江陵・明珠洞', zh:'江陵明珠洞', ko:'강릉 명주동'},
    hangul:'명주동',
    region:{en:'Gangwon coast · KTX 2h', ja:'江原道・KTXで2時間', zh:'江原道海岸 · KTX 2小时', ko:'강원 · KTX 2시간'},
    tagline:{
      en:'Korea’s coffee capital, in alleys of tiled-roof houses near the sea.',
      ja:'海にほど近い、瓦屋根の路地が続く韓国コーヒーの都。',
      zh:'瓦房小巷里的韩国咖啡之都，离海很近。',
      ko:'바다 가까운 기와 골목, 한국 커피의 수도.'},
    tags:{en:['Coffee','Sea','Slow'], ja:['コーヒー','海','スロー'], zh:['咖啡','大海','慢生活'], ko:['커피','바다','슬로우']},
    stats:{station:{en:'Gangneung stn (KTX)', ja:'江陵駅（KTX）', zh:'江陵站（KTX）', ko:'강릉역 (KTX)'},
           walk:{en:'Old town: 20 min radius', ja:'旧市街 徒歩20分圏', zh:'老城区20分钟范围', ko:'구도심 20분 반경'},
           best:{en:'Morning to sunset', ja:'朝〜日没', zh:'清晨到日落', ko:'아침–일몰'}},
    story:{
      en:'Two hours from Seoul by KTX, Gangneung grew Korea’s first real coffee culture. In Myeongju-dong, the old administrative quarter, baristas brought tiled-roof houses and a rice mill back to life as cafes — and the old town has been picked for a five-year national program, running from 2026, to revive its commercial district. Have your coffee in the alleys, then take a bus to Anmok Beach, where cafes line the sand.',
      ja:'ソウルからKTXで2時間。江陵は韓国で最初に本物のコーヒー文化が育った町です。旧官庁街の明珠洞では、バリスタたちが瓦屋根の家や精米所をカフェに再生。2026年から5年間続く国の商圏活性化事業の対象地にも選ばれています。路地でコーヒーを飲んだら、バスで安木海岸へ。砂浜沿いにカフェが並びます。',
      zh:'从首尔坐KTX两小时就到江陵，这里是韩国最早孕育出真正咖啡文化的城市。在旧行政中心明珠洞，咖啡师们把瓦房和碾米厂改造成了咖啡馆——这片老城区还入选了从2026年起为期五年的国家商圈振兴项目。在小巷里喝完咖啡，再坐公交去安木海滩，那里的咖啡馆沿着沙滩一字排开。',
      ko:'서울에서 KTX로 2시간, 강릉은 한국에서 처음으로 진짜 커피 문화가 자란 도시예요. 옛 행정 중심지인 명주동에서는 바리스타들이 기와집과 방앗간을 카페로 되살렸고, 이 구도심은 2026년부터 5년간 이어지는 국가 상권활성화사업 대상지로도 뽑혔어요. 골목에서 커피를 마신 뒤엔 버스를 타고 카페가 늘어선 안목해변으로 가 보세요.'},
    route:[
      {time:'10:30', t:{en:'Jang-kalguksu at Beoljip', ja:'ボルチプでチャンカルグクス', zh:'在Beoljip（벌집）吃酱刀切面', ko:'벌집에서 장칼국수'},
       d:{en:'One dish only, ₩9,000, and they close when the ingredients run out. Closed Tuesdays — and since the cafe Bongbong Bangagan is closed Sundays and Mondays, this route works Wednesday to Saturday.', ja:'メニューは一つ、₩9,000。材料がなくなり次第終了、火曜休み。カフェのボンボンが日・月休みなので、このコースは水〜土向けです。', zh:'只有一道菜，₩9,000，卖完就收，周二休息。加上Bongbong咖啡馆周日周一休息，这条线适合周三到周六。', ko:'메뉴는 하나, 9,000원. 재료 떨어지면 마감이고 화요일은 휴무예요. 봉봉방앗간이 일·월에 쉬니 이 코스는 수~토에 맞습니다.'}},
      {time:'11:30', t:{en:'Gangneung Daedohobu Gwana', ja:'江陵大都護府官衙', zh:'江陵大都护府官衙', ko:'강릉대도호부관아'},
       d:{en:'Free to walk into, 180 meters from the coffee alley, with the national-treasure gate of Imyeonggwan on the grounds.', ja:'入場無料、コーヒー路地から180m。敷地には国宝の臨瀛館三門があります。', zh:'免费入内，距咖啡小巷180米，院内有国宝临瀛馆三门。', ko:'무료입장, 커피 골목에서 180m. 국보인 임영관 삼문이 있습니다.'}},
      {time:'12:15', t:{en:'Coffee at Bongbong, then the archive', ja:'ボンボンでコーヒー、その後アーカイブへ', zh:'在Bongbong喝咖啡，再看档案馆', ko:'봉봉에서 커피, 그다음 아카이브'},
       d:{en:'Hand-drip coffee in the old rice mill. Myeongju Sarangchae is 70 meters away and closes for a midday break from 12:00 to 13:00, so head over after that.', ja:'旧精米所でハンドドリップを一杯。明珠サランチェは70m先、12〜13時は休憩なのでその後に。', zh:'在旧碾米厂喝杯手冲。明珠舍廊斋就在70米外，12点到13点休息，之后再过去。', ko:'옛 방앗간에서 핸드드립 한 잔. 명주사랑채는 70m 거리인데 12~13시가 휴게라 그 뒤에 들르세요.'}},
      {time:'14:00', t:{en:'Gangneung Jungang Market', ja:'江陵中央市場', zh:'江陵中央市场', ko:'강릉중앙시장'},
       d:{en:'A short walk east — about 640 meters as the crow flies. Street snacks on the ground floor, a fish market below, restaurants upstairs.', ja:'東へ少し歩きます（直線で約640m）。1階は食べ歩き、地下は魚市場、2階は食堂街。', zh:'往东走一小段，直线距离约640米。一层小吃，地下是鱼市，二层是餐厅。', ko:'동쪽으로 조금 걸어요. 직선거리로 640m쯤. 1층은 먹거리, 지하는 어시장, 2층은 식당가.'}},
    ],
    spots:[
      {id:'bongbong', name:'Bongbong Bangagan', ko:'봉봉방앗간', cat:{en:'Cafe in an old rice mill', ja:'旧精米所カフェ', zh:'老碾米厂咖啡馆', ko:'방앗간 카페'}, price:'₩₩', checked:'2026-09',
       badges:['card'],
       tip:{en:'A 1940s rice mill, a cafe since 2011, its name painted straight onto the outside wall. New beans arrive by the month rather than the week.', ja:'1940年代の精米所が2011年にカフェへ。外壁には店名がペンキで直接書かれています。新しい豆は週ごとではなく、月ごとに入ってきます。', zh:'1940年代的碾米厂，2011年改成咖啡馆，店名直接漆在外墙上。新豆按月更新，而不是按周。', ko:'1940년대 방앗간을 2011년에 카페로 바꿨어요. 외벽엔 상호를 페인트로 직접 칠해 놨어요. 새 원두는 주 단위가 아니라 달 단위로 들어와요.'},
       order:{en:'The hand-drip list is in Korean and it is bean names only — point at the one you want.', ja:'ハンドドリップのメニューは豆の名前が韓国語で並ぶだけ。飲みたい豆を指差せば大丈夫です。', zh:'手冲菜单是韩文，上面只列着豆子的名字，指一下想喝的那款就行。', ko:'핸드드립은 원두 이름만 한글로 적혀 있어요. 마시고 싶은 원두를 가리키면 됩니다.'}},
      {id:'sarangchae', name:'Myeongju Sarangchae', ko:'명주사랑채', cat:{en:'Coffee-festival archive', ja:'コーヒー祭りのアーカイブ館', zh:'咖啡节档案馆', ko:'커피 아카이브 전시관'}, checked:'2026-09',
       badges:['veg'],
       tip:{en:'Not a local-history house: it archives the Gangneung Coffee Festival back to the first one in 2009 — old posters, festival mugs, brewing gear, coffee books.', ja:'町の歴史館ではありません。2009年の第1回から続く江陵コーヒー祭りのアーカイブで、歴代ポスター、記念マグ、抽出器具、コーヒーの本が並びます。', zh:'这里不是地方史展馆，而是江陵咖啡节的档案馆：从2009年第一届起的海报、纪念马克杯、冲煮器具和咖啡书籍。', ko:'동네 역사관이 아니라 강릉커피축제 아카이브예요. 2009년 제1회부터 이어진 축제의 포스터, 기념 머그컵, 커피 기구, 커피 책이 모여 있어요.'},
       order:{en:'Open 09:00–18:00 with a break from noon to one, closed Mondays. No admission price is published anywhere, so check at the door. Coffee sessions and one-day classes are booked through the Gangneung Cultural Foundation site.', ja:'09:00〜18:00、12〜13時は休憩、月曜休み。入館料はどこにも公表されていないので、入口で確認してください。コーヒー体験やワンデイクラスは江陵文化財団のサイトから予約します。', zh:'09:00–18:00开放，12点到13点休息，周一闭馆。门票价格没有任何公开信息，请到门口确认。咖啡体验与一日课程通过江陵文化财团网站预约。', ko:'09~18시, 12~13시 휴게, 월요일 휴무. 입장료는 공개된 정보가 없어서 현장에서 확인하는 게 좋아요. 커피 체험과 원데이클래스는 강릉문화재단 홈페이지에서 예약해요.'}},
      {id:'gwana', name:'Gangneung Daedohobu Gwana', ko:'강릉대도호부관아', cat:{en:'Old government seat, national treasure', ja:'旧官衙跡・国宝の門', zh:'古官衙遗址·国宝之门', ko:'옛 관아 터 · 국보'}, price:'FREE', checked:'2026-09',
       badges:[],
       tip:{en:'Founded in 936 and about 180 meters from the coffee alley — free to walk into, with the national-treasure gate of Imyeonggwan on the grounds.', ja:'936年創建、コーヒー路地から約180m。入場無料で、敷地には国宝の臨瀛館三門があります。', zh:'始建于936年，距咖啡小巷约180米。免费入内，院内有国宝临瀛馆三门。', ko:'936년에 창건됐고 커피 골목에서 180m쯤. 무료로 들어갈 수 있고, 국보인 임영관 삼문이 있습니다.'},
       order:{en:'Free, so there is no ticket desk. Opening hours are listed differently by different sources, so do not count on a late visit.', ja:'無料なのでチケット売り場はありません。開放時間は資料によって違うので、遅い時間はあてにしない方が無難です。', zh:'免费，所以没有售票处。各处资料标示的开放时间不一致，别指望太晚还能进。', ko:'무료라 매표소가 없어요. 개방 시간은 자료마다 달라서 늦은 시간은 기대하지 않는 게 좋습니다.'}},
      {id:'beoljip', name:'Beoljip', ko:'벌집', cat:{en:'Jang-kalguksu, one dish only', ja:'チャンカルグクスだけの店', zh:'只做酱刀切面', ko:'장칼국수 단일 메뉴'}, price:'₩', checked:'2026-09',
       badges:['queue'],
       tip:{en:'One dish, one price: jang-kalguksu at ₩9,000, in a broth built on gochujang the house ferments itself. There is a floor-seating room at the back.', ja:'メニューはチャンカルグクス₩9,000のみ。自家製コチュジャンのスープです。奥には座敷の部屋があります。', zh:'只有一道菜、一个价：酱刀切面₩9,000，汤底用店里自己发酵的辣椒酱。里头还有一间席地而坐的房间。', ko:'메뉴는 장칼국수 하나, 9,000원. 직접 담근 고추장으로 끓인 국물이에요. 안쪽엔 좌식 방이 있습니다.'},
       order:{en:'Open 10:30–18:20 with a long break from 14:40 to 17:00, closed Tuesdays, and it shuts early when the ingredients run out. Come at opening or after five unless you want to wait 20–60 minutes.', ja:'10:30〜18:20、14:40〜17:00は中休み、火曜休み。材料がなくなり次第終了です。20〜60分待ちたくなければ開店直後か17時以降に。', zh:'10:30–18:20营业，14:40至17:00中间休息，周二不营业，材料用完会提前打烊。不想等20到60分钟的话，就赶在刚开门时或五点以后来。', ko:'10:30~18:20, 14:40~17:00은 브레이크타임, 화요일 휴무. 재료가 떨어지면 일찍 닫아요. 20~60분 기다리기 싫으면 오픈 직후나 5시 이후에.'}},
      {id:'jungangmarket', name:'Gangneung Jungang Market', ko:'강릉중앙시장', cat:{en:'Covered market, three levels', ja:'3層の伝統市場', zh:'三层的传统市场', ko:'전통시장'}, price:'₩', checked:'2026-09',
       badges:[],
       tip:{en:'Three levels: a fish market in the basement, dried seafood and street snacks on the ground floor, restaurants upstairs. It is the biggest octopus market in the Yeongdong region, the east side of Gangwon, and the dakgangjeong got famous off a TV show.', ja:'3層構造。地下1階は魚市場、1階は乾物と食べ歩き、2階は食堂街。嶺東（江原道の東側）で最大のタコ市場で、タッカンジョンはテレビ番組で有名になりました。', zh:'三层结构：地下一层鱼市，一层干货与街头小吃，二层餐厅。这里是岭东地区最大的章鱼市场，甜脆炸鸡也因综艺节目而出名。', ko:'지하 1층 어시장, 1층 건어물과 먹거리, 2층 식당가. 영동 지역 최대 문어시장이고, 닭강정은 예능 프로그램으로 유명해졌어요.'},
       order:{en:'Open all year, about 640 meters from Myeongju-dong. Upstairs is where you sit down — samsugi-tang, a peppery sculpin stew, is the local order.', ja:'年中無休、明珠洞から約640m。座って食べるなら2階へ。地元の一杯はサムスギタン（カジカの辛いスープ）です。', zh:'全年无休，距明珠洞约640米。想坐下来吃就上二楼，本地人点的是辣味杜父鱼汤（삼숙이탕）。', ko:'연중무휴, 명주동에서 640m쯤. 앉아서 먹으려면 2층으로. 현지인들은 삼숙이탕을 시킵니다.'}},
      {id:'imdangchurch', name:'Imdang-dong Catholic Church', ko:'임당동성당', cat:{en:'1955 Gothic church, listed heritage', ja:'1955年のゴシック聖堂・登録文化財', zh:'1955年哥特式教堂·登录文化遗产', ko:'1955년 고딕 성당 · 등록문화유산'}, price:'FREE', checked:'2026-09',
       badges:[],
       tip:{en:'Built in 1955 and listed as national heritage in 2010 — a pointed bell tower, arched windows, buttresses, and stained glass by Father Cho Kwang-ho inside. Gangneung’s oldest parish.', ja:'1955年竣工、2010年に国家登録文化遺産に。尖った鐘塔、アーチ窓、バットレス（控え壁）、内部にはチョ・グァンホ神父のステンドグラス。江陵でいちばん古い小教区です。', zh:'1955年建成，2010年列为国家登录文化遗产：尖顶钟楼、拱形窗、扶壁，室内有曹光镐神父的彩色玻璃。江陵最古老的堂区。', ko:'1955년에 지어 2010년 국가등록문화유산이 됐어요. 뾰족한 종탑, 아치 창, 버팀벽, 안에는 조광호 신부의 스테인드글라스. 강릉에서 가장 오래된 본당입니다.'},
       order:{en:'A working church, so keep it quiet if Mass is on. The parish began in 1921 and moved to this site in 1934; pilgrims can collect a stamp here.', ja:'現役の教会なのでミサ中は静かに。1921年に司牧を始め、1934年に現在地へ移りました。巡礼スタンプもあります。', zh:'这是仍在使用的教堂，弥撒时请保持安静。堂区始于1921年，1934年迁到现址；朝圣者可以在这里盖章。', ko:'실제 미사가 열리는 성당이라 미사 중엔 조용히. 1921년 사목을 시작해 1934년 지금 자리로 옮겼고, 순례 스탬프도 있습니다.'}},
    ]
  },

  /* ============ GONGJU — preview ============ */
  {
    id:'gongju', tile:'제민천', tileClass:'t-gongju', full:true, longTile:true, mapArea:'공주 제민천',
    name:{en:'Gongju Jemincheon', ja:'公州・済民川', zh:'公州济民川', ko:'공주 제민천'},
    hangul:'제민천',
    region:{en:'Chungnam · KTX+bus 1.5h', ja:'忠南・KTX+バス1.5時間', zh:'忠南 · KTX+巴士1.5小时', ko:'충남 · KTX+버스 1.5시간'},
    tagline:{
      en:'A stream-side village of hanok stays, tea houses and tiny bookshops.',
      ja:'小川沿いに韓屋の宿、茶房、小さな本屋が並ぶ村。',
      zh:'溪水边的韩屋民宿、茶室与迷你书店之村。',
      ko:'개천을 따라 한옥 스테이, 찻집, 작은 책방.'},
    tags:{en:['Hanok','Tea','Quiet'], ja:['韓屋','お茶','静けさ'], zh:['韩屋','茶','安静'], ko:['한옥','차','고요']},
    stats:{station:{en:'Gongju terminal + 10 min', ja:'公州ターミナル＋10分', zh:'公州客运站+10分钟', ko:'공주터미널 + 10분'},
           walk:{en:'Along the stream: 15 min', ja:'川沿い徒歩15分', zh:'沿溪步行15分钟', ko:'개천 따라 15분'},
           best:{en:'Overnight stay', ja:'一泊がおすすめ', zh:'建议住一晚', ko:'1박 추천'}},
    story:{
      en:'Gongju was the capital of the ancient Baekje kingdom; Jemincheon is the stream that runs through its old town. Young returnees turned emptying houses into a “village hotel” — a village desk in one alley, guest rooms in another, breakfast laid out in the house where you sleep. Stay a night, walk to the fortress at dusk, and you’ll have Korea’s history quarter almost to yourself.',
      ja:'公州は古代百済の都。済民川は旧市街を流れる小川です。Uターンした若者たちが空き家を「マウルホテル（村のホテル）」に生まれ変わらせました。案内所はこの路地、客室はあの路地、朝食は泊まった家の中で。一泊して夕暮れの公山城まで歩けば、韓国の歴史地区をほぼ独り占めできます。',
      zh:'公州是古代百济王国的都城，济民川是穿过老城的小溪。返乡青年把空置的房屋改成了“村庄旅馆”——导览处在这条巷，客房在那条巷，早餐就在你住的那栋房子里。住一晚，黄昏时分走到公山城，这片韩国历史街区几乎归你独享。',
      ko:'공주는 백제의 수도였고, 제민천은 구도심을 가로지르는 개천입니다. 돌아온 청년들이 빈집을 "마을호텔"로 바꿨어요. 안내소는 이 골목, 객실은 저 골목, 조식은 묵는 집 안에서. 하루 묵고 해질녘 공산성까지 걸으면, 한국의 역사 동네를 거의 독차지할 수 있습니다.'},
    route:[
      {time:'11:00', t:{en:'Lunch at Gogane Kalguksu', ja:'コガネカルグクスで昼食', zh:'在高家刀切面吃午饭', ko:'고가네칼국수에서 점심'},
       d:{en:'Get there when it opens. It’s closed on Sundays, the museum on Mondays and the tea house on Tuesdays — so this half-day works Wednesday to Saturday.', ja:'開店に合わせて。日曜休み、文学館は月曜、茶房は火曜が休みなので、この半日コースは水〜土向けです。', zh:'赶在开门时到。这里周日休息、文学馆周一闭馆、茶室周二休息，所以这半天行程适合周三到周六。', ko:'문 여는 시간에 맞춰 가세요. 일요일 휴무이고 문학관은 월요일, 찻집은 화요일에 쉬어서 이 반나절 코스는 수~토에 맞습니다.'}},
      {time:'13:00', t:{en:'Pulkkot Literature Museum', ja:'草花文学館', zh:'草花文学馆', ko:'풀꽃문학관'},
       d:{en:'It reopens at one, after the midday break. Free, in an old Japanese-style house, with a new wing added in 2025.', ja:'12〜13時の休憩が明ける13時に入館。無料、日本式の古い家屋で、2025年に新館が加わりました。', zh:'午休结束后13点重新开放。免费，设在一栋日式老宅里，2025年新增了新馆。', ko:'12~13시 휴게가 끝나는 1시에 들어가세요. 무료이고, 일본식 옛 가옥에 2025년 신관이 더해졌습니다.'}},
      {time:'14:30', t:{en:'Tea at Lucia’s Garden', ja:'ルチアの庭でお茶', zh:'在露西亚的庭院喝茶', ko:'루치아의 뜰에서 차 한 잔'},
       d:{en:'Black tea or milk tea with a scone, in a 1960s hanok. Open 12:00–18:30, closed Tuesdays.', ja:'1960年代の韓屋で、紅茶かミルクティーにスコーンを。12:00〜18:30、火曜休み。', zh:'在1960年代的韩屋里，点红茶或奶茶配司康。12:00–18:30营业，周二休息。', ko:'1960년대 한옥에서 홍차나 밀크티에 스콘. 12~18:30 영업, 화요일 휴무.'}},
      {time:'17:00', t:{en:'Gongju Sanseong Market', ja:'公州山城市場', zh:'公州山城市场', ko:'공주산성시장'},
       d:{en:'Walk north along the stream to the market. On Friday and Saturday evenings through October 17, the Bammasil night market runs 17:00–22:00.', ja:'川沿いを北へ歩いて市場へ。10月17日までの金・土は17〜22時にパムマシル夜市が開きます。', zh:'沿着溪流往北走到市场。到10月17日为止，每周五、六17点至22点有夜市。', ko:'개천을 따라 북쪽으로 걸어 시장까지. 10월 17일까지 금·토 17~22시엔 밤마실 야시장이 열립니다.'}},
    ],
    spots:[
      {id:'lucia', name:'Lucia’s Garden', ko:'루치아의 뜰', cat:{en:'Hanok tea house', ja:'韓屋の茶房', zh:'韩屋茶室', ko:'한옥 찻집'}, price:'₩₩', checked:'2026-09',
       badges:['card','veg','queue'],
       tip:{en:'A house built in 1964 and turned into a tea room in 2013, with a courtyard garden behind it.', ja:'1964年に建てられた家屋を、2013年に茶房に改装したお店。奥には中庭があります。', zh:'一栋建于1964年的老宅，2013年改成茶室，后面还有一个庭院。', ko:'1964년에 지은 집을 2013년에 찻집으로 바꿨어요. 뒤편엔 마당 정원이 있어요.'},
       order:{en:'Take your shoes off before stepping onto the maru, the raised wooden floor. Tea also comes as a set with a scone — ₩11,500 with black tea, ₩12,500 with milk tea; black tea on its own is ₩8,000. Open 12:00–18:30, closed Tuesdays, no parking.', ja:'板の間では靴を脱いで。お茶はスコーンとのセットでも頼めます（紅茶₩11,500、ミルクティー₩12,500）。紅茶単品は₩8,000。12:00〜18:30、火曜休み、駐車場なし。', zh:'上木地板要脱鞋。茶也有配司康的套餐：红茶₩11,500，奶茶₩12,500；单点红茶₩8,000。12:00–18:30营业，周二休息，没有停车位。', ko:'마루에선 신발을 벗고. 스콘 세트로도 나와요. 홍차 세트 11,500원, 밀크티 세트 12,500원, 홍차 단품은 8,000원. 12~18:30 영업, 화요일 휴무, 주차 불가.'}},
      {id:'village', name:'Bonghwangjae Hanok', ko:'봉황재 한옥', cat:{en:'Hanok guesthouse, four rooms', ja:'韓屋ゲストハウス・4室', zh:'韩屋民宿·四间客房', ko:'한옥 게스트하우스 · 4객실'}, price:'₩₩₩', checked:'2026-09',
       badges:['card'],
       tip:{en:'A four-room 1960s hanok, one of the houses in Puzzle Lab’s “village hotel.” Breakfast is a simple self-serve spread inside the house, 08:00–10:00; for tips on the neighborhood, ask at Cream, the village information center.', ja:'1960年代の韓屋を使った4室の宿。運営はパズルラボで、「マウルホテル」の一軒です。朝食は宿の中でセルフの軽食（8〜10時）。町の案内は「マウル案内所クリーム」が引き受けています。', zh:'一栋1960年代的韩屋，共四间客房，是Puzzle Lab经营的“村庄旅馆”中的一栋。早餐是屋内的简单自助（8至10点）；想了解街区，就去村庄导览处Cream问问。', ko:'1960년대 한옥에 객실 넷. 퍼즐랩이 마을호텔의 한 채로 운영합니다. 조식은 숙소 안에서 간단한 셀프(8~10시), 동네 안내는 마을안내소 크림이 맡아요.'},
       order:{en:'Book ahead — four rooms only. English booking works through the international travel sites; check-in from 15:00, out by 11:00.', ja:'客室は4つだけなので早めの予約を。英語での予約は海外の旅行サイトから。チェックイン15:00、チェックアウト11:00。', zh:'只有四间房，请提前预订。英文预订可通过国际旅行网站；15:00入住，11:00退房。', ko:'객실이 넷뿐이라 예약은 미리. 영어 예약은 해외 여행 사이트로 가능하고, 체크인 15시·체크아웃 11시.'}},
      {id:'gogane', name:'Gogane Kalguksu', ko:'고가네칼국수', cat:{en:'Noodle hotpot, floor seating', ja:'麺鍋の座敷食堂', zh:'面条火锅·席地座位', ko:'칼국수·국수전골'}, price:'₩', checked:'2026-09',
       badges:['queue'],
       tip:{en:'Korean-wheat noodle hotpot at ₩8,000 — ₩9,000 if you are eating alone — with a small pond and garden out front where people wait. Upstairs is shoes-off floor seating.', ja:'韓国産小麦の麺鍋が₩8,000（1人で注文する場合は₩9,000）。店先の池のある庭で順番を待ちます。2階は靴を脱いで上がる座敷です。', zh:'韩国本土小麦做的面条火锅₩8,000，一个人点是₩9,000。店门口有个带小池塘的花园，客人就在那儿等位。二楼是要脱鞋的席地座位。', ko:'우리밀 국수전골 8,000원, 1인 주문은 9,000원. 가게 앞 연못 딸린 정원에서 기다립니다. 2층은 신발 벗는 좌식이에요.'},
       order:{en:'Open Monday to Saturday, closed Sundays, with a break from 15:00 to 17:00. At peak times you write your name on the waiting list — one visitor in 2025 reported a wait of about thirty minutes.', ja:'月〜土営業、日曜休み、15〜17時は中休み。混む時間は名簿に名前を書いて待ちます。2025年の訪問記では約30分待ちでした。', zh:'周一至周六营业，周日不营业，15点到17点中间休息。高峰时段要在名单上写名字等位——据2025年的一篇探店记录，当时大约等了三十分钟。', ko:'월~토 영업, 일요일 휴무, 15~17시는 브레이크타임. 붐빌 땐 명단에 이름을 적고 기다려요. 2025년 한 방문기에선 30분쯤 기다렸다고 해요.'}},
      {id:'pulkkot', name:'Pulkkot Literature Museum', ko:'나태주풀꽃문학관', cat:{en:'Poetry museum, free', ja:'詩の文学館・無料', zh:'诗歌文学馆·免费', ko:'문학관 · 무료'}, price:'FREE', checked:'2026-09',
       badges:[],
       tip:{en:'A museum for the poet Na Tae-ju, best known for the short poem “Pulkkot” (Grass Flower). It opened in an old Japanese-style house in October 2014 and gained a new wing in July 2025; the Pulkkot literary prize is awarded from here.', ja:'「草花（プルコッ）」という短い詩で知られる詩人ナ・テジュの文学館。2014年10月に日本式の古い家屋で開館し、2025年7月に新館が加わりました。草花文学賞もここから贈られます。', zh:'为诗人罗泰柱而设的文学馆，他最广为人知的是短诗《草花》。2014年10月在一栋日式老宅中开馆，2025年7月增建新馆；草花文学奖也由此颁出。', ko:'짧은 시 "풀꽃"으로 알려진 나태주 시인의 문학관이에요. 2014년 10월 일본식 옛 가옥에서 문을 열었고 2025년 7월 신관이 더해졌습니다. 풀꽃문학상도 여기서 줍니다.'},
       order:{en:'Free, Tuesday to Sunday 10:00–17:00 with a break from noon to one, closed Mondays. Thirty parking spaces; no pets.', ja:'無料、火〜日10:00〜17:00（12〜13時休憩）、月曜休館。駐車30台、ペット同伴不可。', zh:'免费，周二至周日10:00–17:00（12点至13点休息），周一闭馆。停车30个车位；不可带宠物。', ko:'무료, 화~일 10~17시(12~13시 휴게), 월요일 휴관. 주차 30대, 반려동물은 들어갈 수 없어요.'}},
      {id:'hoseo', name:'1967 Hoseo Theater', ko:'1967 호서극장', cat:{en:'Media-art hall in an old cinema', ja:'旧映画館のメディアアート館', zh:'老电影院改造的媒体艺术馆', ko:'옛 극장 · 미디어아트'}, price:'₩', checked:'2026-09',
       badges:[],
       tip:{en:'The town cinema — opened 1963, rebuilt 1967, dark since 1995 — came back in July 2026 as a media-art hall. A 21-meter-wide LED wall on the ground floor, the old projection room recreated upstairs, and a terrace overlooking the stream.', ja:'1963年開館、1967年改築、1995年閉館だった町の映画館が、2026年7月にメディアアート館として復活。1階に横21mのLEDウォール、上階には旧映写室の再現と済民川を見下ろすテラスがあります。', zh:'这家小城电影院1963年开业、1967年改建、1995年关门，2026年7月以媒体艺术馆的身份重开。一层有21米宽的LED墙，楼上复原了旧放映室，还有俯瞰济民川的观景台。', ko:'1963년에 문을 열어 1967년에 고쳐 지었다가 1995년에 문을 닫은 동네 극장이, 2026년 7월 미디어아트 공간으로 돌아왔어요. 1층엔 가로 21m LED 월이 있고, 위층엔 옛 영사실을 재현한 공간과 제민천이 내려다보이는 전망대가 있어요.'},
       order:{en:'Open 12:00–21:00, Tuesday to Sunday. Closed Mondays (if a Monday is a public holiday, it closes the following day instead) and on Lunar New Year’s Day and Chuseok Day. Current admission prices aren’t listed online — ask at the desk.', ja:'火〜日12:00〜21:00、月曜休館（祝日なら翌日）、旧正月・秋夕当日も休み。現在の観覧料はオンラインに出ていないので、受付で確認を。', zh:'周二至周日12:00–21:00开放，周一闭馆（逢节假日顺延），春节与中秋当天休息。目前的门票价格网上没有公布，请到前台询问。', ko:'화~일 12~21시, 월요일 휴관(공휴일이면 다음 날), 설날·추석 당일도 쉽니다. 지금 관람료는 온라인에 안 나와 있으니 현장에서 확인하세요.'}},
      {id:'sanseong', name:'Gongju Sanseong Market', ko:'공주산성시장', cat:{en:'Traditional market since 1937', ja:'1937年開設の伝統市場', zh:'1937年开设的传统市场', ko:'전통시장 · 1937년 개설'}, price:'₩', checked:'2026-09',
       badges:[],
       tip:{en:'Open since 1937, below the fortress hill. The traditional market days fall on dates ending in 1 and 6 — the 1st, 6th, 11th and so on — and that is when the outer stalls fill up.', ja:'1937年に開かれた、公山城のふもとの市場。1と6のつく日（1日、6日、11日…）が市の日で、その日は外の露店まで埋まります。', zh:'1937年开市，就在公山城脚下。逢1和6的日子（1日、6日、11日……）是集市日，那天外圈的露天摊位也会摆满。', ko:'1937년에 문을 연, 공산성 아래 시장이에요. 날짜 끝자리가 1·6인 날(1일, 6일, 11일…)이 장날이라, 그날은 바깥 노점까지 꽉 들어차요.'},
       order:{en:'08:00–19:00, though each shop has its own days off. On Friday and Saturday evenings through October 17, 2026, the Bammasil night market runs 17:00–22:00 with food stalls.', ja:'08:00〜19:00（休みは店ごとに違います）。2026年10月17日までの金・土は17:00〜22:00に「パムマシル夜市」が立ち、屋台が並びます。', zh:'08:00–19:00，各家店的休息日不一样。到2026年10月17日为止，每周五、六17:00至22:00有夜市，摆出各种小吃摊。', ko:'08~19시, 쉬는 날은 점포마다 달라요. 2026년 10월 17일까지 금·토 저녁엔 17~22시에 밤마실 야시장이 열립니다.'}},
    ]
  },
];
